baseURL = 'https://spsree4u.github.io'
languageCode = 'en-us'
title = 'sreejith_puthanveedu'
theme = "hugo-theme-console"

[params]

  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn slow"

  [[params.navlinks]]
  name = "projects"
  url = "projects/"

  [[params.navlinks]]
  name = "blogs"
  url = "blogs/"
